### ISSUE TITLE
Program crashes System.MissingMethodException: Method not found: 'System.Type System.Runtime.InteropServices.Marshal.GetTypeFromCLSID(System.Guid)'.

### ISSUE THREAD

**Issue by dm8tbr** [bcleary/outlook-gmail-rules-export#3]
Unhandled Exception: System.MissingMethodException: Method not found: 'System.Type System.Runtime.InteropServices.Marshal.GetTypeFromCLSID(System.Guid)'.
   at OutlookRulesExport.Program.GetStore(String storeName)
   at OutlookRulesExport.Program.Main(String[] args)

I guess something in my ruleset trips it up?
Thanks for your efforts, I'm sure there are others who appreciate them too.

**Comment by dm8tbr** [comment]
Just in case I reinstalled the libraries for .net 4.0 - that didn't help.
I'm currently upgrading my outlook from 2007 to 2010 to see if that helps.
I only need it to migrate my rules, it's google apps from now on anyway...

**Comment by bcleary** [comment]
Thanks for the bug report dm8tbr. While it should work in theory I have not personally tested this with 2007. I have a feeling that might be the issue your having. I'll see if I can get a VM up and running with office 2007 and reproduce today. If upgrading to 2010 doesn't solve the problem let me know.

**Comment by dm8tbr** [comment]
Sadly the update to 2010 didn't seem to do the trick. Same message as before.
Which .net libraries were you using? I could add 4.5 to the mix on that machine.

**Comment by bcleary** [comment]
I built the binary against 4.5 on my machine, but I think you should be getting a prompt to update if its a .net version issue.

**Comment by dm8tbr** [comment]
Installing 4.5 did the trick.
Just tried it with '-s' and got a list.
I'm going to recommend your tool with the note that it needs 4.5, we've got an massive move ongoing and I'm luckily in the pilot group. :-)

**Comment by bcleary** [comment]
Glad that worked for you. I'll add a note to the system requirements. If you guys implement any new rules fee free to send me a pull request.

**Comment by bcleary** [comment]
Just to note, I just ran a quick test of the tool against Outlook 2007 running in a VM. Everything looks good. Have updated the system requirements with support for 2007 and noted the requirement for .Net 4.5
