### ISSUE TITLE
Allow spaces in Mailbox names passed as a parameter.

### ISSUE THREAD

**Issue by dm8tbr** [bcleary/outlook-gmail-rules-export#4]
Here is the type of output I get on my mailbox:

> ...>OutlookRulesExport.exe -s
> Mailbox - Ruecker Thomas
> Public Folders - firstname.lastname@example.org
> SharePoint Lists
> Archive Folders

I've gone through various permutations of escaping the input to no effect:

> ...>OutlookRulesExport.exe Ruecker Thomas
> ...>OutlookRulesExport.exe firstname.lastname@example.org
> ...>OutlookRulesExport.exe Ruecker^ Thomas
> ...>OutlookRulesExport.exe "Ruecker Thomas"
> ...>set MAILBOX=Ruecker Thomas
> ...>OutlookRulesExport.exe %MAILBOX%

I hoped this would be an easy fix. Sadly I don't even have a Windows dev env set up, otherwise I'd have taken a stab at preparing a patch myself, also I took a look at how other people approach this and it seems to be a world of pain due to space being 'special' and automatically used as an argument separator. :-/

If you don't know better either, then as a ugly 'hack' I'd propose to substitute some char that's illegal in a mailbox name, but will get passed from CLI, e.g. something like '/' (I searchd the intarwebz and KB841091 lists it, but better take a look yourself)

**Comment by bcleary** [comment]
I think using quotes around the full mailbox name should work. 

Can you try OutlookRulesExport.exe "Mailbox - Ruecker Thomas"

If this doesn't work i can quickly patch it for you.

**Comment by dm8tbr** [comment]
Yay! That worked! I now have an XML file and it also produces CSV output.
Thanks so much for your help! You can close both issues now.

**Comment by bcleary** [comment]
Excellent, note on the CSV output I noticed a small error today that i will fix shortly. Its not printing all supported rules to CSV.
